dist: trusty

language: node_js
node_js:
  - "10"

stages:
    - script
    - deploy

before_install:
    - cd src/react-calculator

# https://github.com/dwyl/learn-travis/issues/35
# script: echo "npm test temporarily disabled"

script:
    - echo "npm test temporarily disabled"
    - npm run-script build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: pick1a1username/react-calculator-hosting
    keep_history: true
    local_dir: /src/react-calculator/build
    target_branch: master
    on:
        branch: travis_ui_setup
    