dist: trusty

language: node_js
node_js:
  - "10"

stages:
    - build

before_install:
    - cd src/react-calculator

# https://github.com/dwyl/learn-travis/issues/35
script: echo "npm test temporarily disabled"

build:
    - npm run-script build